name: DevOps CI-CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  test_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: 1. Pruebas Automatizadas (Validar YAML)
        run: docker-compose config

      - name: 2. Copiar archivos al Servidor Linux (EC2)
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "."
          target: "/home/ubuntu/proyecto_docker"

      - name: 3. Construcción, Despliegue y Rollback en EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/proyecto_docker
            chmod +x deploy.sh
            ./deploy.sh